name: Build

on:
  workflow_dispatch:
    inputs:
      url_dm1q:
        description: 'S23 SamFW Direct Download Link'
        required: true
      url_dm2q:
        description: 'S23+ SamFW Direct Download Link'
        required: true
      url_dm3q:
        description: 'S23U SamFW Direct Download Link'
        required: true
      triplet_dm1q:
        description: 'Downloaded firmware triplet'
        required: true
        default: "S911BXXS9EZCI/S911BOXM9EZCI/S911BXXS9EZCI"
      triplet_dm2q:
        description: 'Downloaded firmware triplet'
        required: true
        default: "S916BXXS9EZCI/S916BOXM9EZCI/S916BXXS9EZCI"
      triplet_dm3q:
        description: 'Downloaded firmware triplet'
        required: true
        default: "S918BXXS9EZCI/S918BOXM9EZCI/S918BXXS9EZCI"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        target: [dm1q, dm2q, dm3q]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          submodules: 'recursive'

      - name: Free disk space (1/3)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Free disk space (2/3)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Free disk space (3/3)
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: 'compiler_cmake'

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            7zip attr ccache clang ffmpeg \
            libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev wget \
            libzstd-dev linux-modules-extra-$(uname -r) lld protobuf-compiler webp
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/unica_platform.pk8
          echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/unica_platform.x509.pem
          echo -n "${{ secrets.OTA_KEY_PK8 }}" | base64 --decode > security/unica_ota.pk8
          echo -n "${{ secrets.OTA_KEY_PEM }}" | base64 --decode > security/unica_ota.x509.pem

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build dependencies
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/build_dependencies.sh

      - name: Download stock firmwares
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/download_fw.sh --ignore-target
          if [[ "${{ matrix.target }}" == "dm1q" ]]; then
            MODEL="SM-S911B"
            TRIPLET="${{ github.event.inputs.triplet_dm1q }}"
            TARGET_URL="${{ github.event.inputs.url_dm1q }}"
          elif [[ "${{ matrix.target }}" == "dm2q" ]]; then
            MODEL="SM-S916B"
            TRIPLET="${{ github.event.inputs.triplet_dm2q }}"
            TARGET_URL="${{ github.event.inputs.url_dm2q }}"
          elif [[ "${{ matrix.target }}" == "dm3q" ]]; then
            MODEL="SM-S918B"
            TRIPLET="${{ github.event.inputs.triplet_dm3q }}"
            TARGET_URL="${{ github.event.inputs.url_dm3q }}"
          fi
          echo "- Processing ${MODEL} firmware with EUX CSC"
          echo "    - Downloading ${TRIPLET}..."
          mkdir -p "./out/odin/${MODEL}_EUX"
          wget -q --no-check-certificate --content-disposition "${TARGET_URL}" --directory-prefix="./out/odin/${MODEL}_EUX"
          touch "./out/odin/${MODEL}_EUX/.downloaded"
          echo "${TRIPLET}" >> "./out/odin/${MODEL}_EUX/.downloaded"
          ZIP_FILE="$(find "out/odin/${MODEL}_EUX" -name "*.zip" | sort -r | head -n 1)"
          echo "- Extracting $(basename "$ZIP_FILE")..."
          unzip -o "$ZIP_FILE" -d "out/odin/${MODEL}_EUX" && rm -rf "$ZIP_FILE"

      - name: Extract stock firmwares
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/extract_fw.sh

      - name: Build ROM
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/make_rom.sh -z

      - name: Upload to GoFile
        run: |
          ZIP_FILE=$(find out -maxdepth 1 -type f -name "*sign.zip" | head -n 1)
          RESPONSE=$(curl -s -F "file=@$ZIP_FILE" -F "token=${{ secrets.GOFILE_TOKEN }}" -F "folderId=${{ secrets.GOFILE_FOLDER }}" "https://upload-eu-par.gofile.io/uploadFile")
          echo "Download link:"
          echo "$RESPONSE" | jq -r '.data.downloadPage'
